// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  biography: dynamic(() => import('./Biography')),
  content: dynamic(() => import('./Content')),
  content_index: dynamic(() => import('./ContentIndex')),
  experience: dynamic(() => import('./Experience')),
  hero: dynamic(() => import('./Hero')),
  marquee: dynamic(() => import('./Marquee')),
  opt_out: dynamic(() => import('./OptOut')),
  references: dynamic(() => import('./References')),
}
