// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  content: dynamic(() => import('./Content')),
  content_index: dynamic(() => import('./ContentIndex')),
  hero: dynamic(() => import('./Hero')),
}
